import HodgeProofHP.Stage3GaussianL2Domain
import HodgeProofHP.Stage3HarmonicActionAE
import HodgeProofHP.Stage3GaussianPointwiseAction

/-! Exact declarations needed for the Gaussian eigenvalue proof. -/

#check HodgeProofHP.hpRealGaussian_harmonic_pointwise
#check HodgeProofHP.hpSchwartzSecondDeriv_apply
#check HodgeProofHP.hpSchwartzQuadraticMul_apply
#check HodgeProofHP.hpHarmonicCoreOperator_apply_ae
#check HodgeProofHP.hpHarmonicCoreOperator_apply
#check HodgeProofHP.hpGaussianGroundL2_apply_ae
#check HodgeProofHP.hpGaussianGroundL2_eq_schwartz
#check HodgeProofHP.hpGaussianGroundL2_mem_harmonic_domain
