import HodgeProofHP.Stage4ThetaHankelAdjointSquareKernel

/-!
Audit of the verified theta Hankel operator frontier.
The accompanying script examines the installed spectral API.
-/

namespace HodgeProofHP

#check HPThetaHankelSpace
#check hpThetaHankelOperator
#check hpThetaHankelOperator_isCompact
#check hpThetaHankelOperator_isSelfAdjoint

#check hpThetaHankelAdjointSquare
#check hpThetaHankelAdjointSquare_isCompact
#check hpThetaHankelAdjointSquare_isSelfAdjoint
#check hpThetaHankelAdjointSquare_isSymmetric

#check hpThetaHankelAdjointSquare_eigenvalue_real_nonneg
#check hpThetaHankelAdjointSquare_apply_eq_zero_iff
#check hpThetaHankelAdjointSquare_eigenvalue_energy_quotient

#print axioms hpThetaHankelAdjointSquare_isCompact
#print axioms hpThetaHankelAdjointSquare_isSelfAdjoint
#print axioms hpThetaHankelAdjointSquare_eigenvalue_real_nonneg

end HodgeProofHP
