import HodgeProofHP.Stage5ThetaJensenCellsBatch000
import HodgeProofHP.Stage5ThetaJensenCellsBatch001
import HodgeProofHP.Stage5ThetaJensenCellsBatch002
import HodgeProofHP.Stage5ThetaJensenCellsBatch003
import HodgeProofHP.Stage5ThetaJensenCellsBatch004
import HodgeProofHP.Stage5ThetaJensenCellsBatch005
import HodgeProofHP.Stage5ThetaJensenCellsBatch006
import HodgeProofHP.Stage5ThetaJensenCellsBatch007
import HodgeProofHP.Stage5ThetaJensenCellsBatch008
import HodgeProofHP.Stage5ThetaJensenCellsBatch009
import HodgeProofHP.Stage5ThetaJensenCellsBatch010
import HodgeProofHP.Stage5ThetaJensenCellsBatch011
import HodgeProofHP.Stage5ThetaJensenCellsBatch012
import HodgeProofHP.Stage5ThetaJensenCellsBatch013
import HodgeProofHP.Stage5ThetaJensenCellsBatch014
import HodgeProofHP.Stage5ThetaJensenCellsBatch015
import HodgeProofHP.Stage5ThetaJensenCellsBatch016
import HodgeProofHP.Stage5ThetaJensenCellsBatch017
import HodgeProofHP.Stage5ThetaJensenCellsBatch018
import HodgeProofHP.Stage5ThetaJensenCellsBatch019
import HodgeProofHP.Stage5ThetaJensenCellsBatch020
import HodgeProofHP.Stage5ThetaJensenCellsBatch021
import HodgeProofHP.Stage5ThetaJensenCellsBatch022
import HodgeProofHP.Stage5ThetaJensenCellsBatch023
import HodgeProofHP.Stage5ThetaJensenCellsBatch024
import HodgeProofHP.Stage5ThetaJensenCellsBatch025
import HodgeProofHP.Stage5ThetaJensenCellsBatch026
import HodgeProofHP.Stage5ThetaJensenCellsBatch027
import HodgeProofHP.Stage5ThetaJensenCellsBatch028
import HodgeProofHP.Stage5ThetaJensenCellsBatch029
import HodgeProofHP.Stage5ThetaJensenCellsBatch030
import HodgeProofHP.Stage5ThetaJensenCellsBatch031
import HodgeProofHP.Stage5ThetaJensenCellsBatch032
import HodgeProofHP.Stage5ThetaJensenCellsBatch033
import HodgeProofHP.Stage5ThetaJensenCellsBatch034
import HodgeProofHP.Stage5ThetaJensenCellsBatch035
import HodgeProofHP.Stage5ThetaJensenCellsBatch036
import HodgeProofHP.Stage5ThetaJensenCellsBatch037
import HodgeProofHP.Stage5ThetaJensenCellsBatch038
import HodgeProofHP.Stage5ThetaJensenCellsBatch039
import HodgeProofHP.Stage5ThetaJensenCellsBatch040
import HodgeProofHP.Stage5ThetaJensenCellsBatch041
import HodgeProofHP.Stage5ThetaJensenCellsBatch042
import HodgeProofHP.Stage5ThetaJensenCellsBatch043
import HodgeProofHP.Stage5ThetaJensenCellsBatch044
import HodgeProofHP.Stage5ThetaJensenCellsBatch045
import HodgeProofHP.Stage5ThetaJensenCellsBatch046
import HodgeProofHP.Stage5ThetaJensenCellsBatch047
import HodgeProofHP.Stage5ThetaJensenCellsBatch048
import HodgeProofHP.Stage5ThetaJensenCellsBatch049
import HodgeProofHP.Stage5ThetaJensenCellsBatch050
import HodgeProofHP.Stage5ThetaJensenCellsBatch051
import HodgeProofHP.Stage5ThetaJensenCellsBatch052
import HodgeProofHP.Stage5ThetaJensenCellsBatch053
import HodgeProofHP.Stage5ThetaJensenCellsBatch054
import HodgeProofHP.Stage5ThetaJensenCellsBatch055
import HodgeProofHP.Stage5ThetaJensenCellsBatch056
import HodgeProofHP.Stage5ThetaJensenCellsBatch057
import HodgeProofHP.Stage5ThetaJensenCellsBatch058
import HodgeProofHP.Stage5ThetaJensenCellsBatch059
import HodgeProofHP.Stage5ThetaJensenCellsBatch060
import HodgeProofHP.Stage5ThetaJensenCellsBatch061
import HodgeProofHP.Stage5ThetaJensenCellsBatch062
import HodgeProofHP.Stage5ThetaJensenCellsBatch063
import HodgeProofHP.Stage5ThetaJensenCellsBatch064
import HodgeProofHP.Stage5ThetaJensenCellsBatch065
import HodgeProofHP.Stage5ThetaJensenCellsBatch066
import HodgeProofHP.Stage5ThetaJensenCellsBatch067
import HodgeProofHP.Stage5ThetaJensenCellsBatch068
import HodgeProofHP.Stage5ThetaJensenCellsBatch069
import HodgeProofHP.Stage5ThetaJensenCellsBatch070
import HodgeProofHP.Stage5ThetaJensenCellsBatch071
import HodgeProofHP.Stage5ThetaJensenCellsBatch072
import HodgeProofHP.Stage5ThetaJensenCellsBatch073
import HodgeProofHP.Stage5ThetaJensenCellsBatch074
import HodgeProofHP.Stage5ThetaJensenCellsBatch075
import HodgeProofHP.Stage5ThetaJensenCellsBatch076
import HodgeProofHP.Stage5ThetaJensenCellsBatch077
import HodgeProofHP.Stage5ThetaJensenCellsBatch078
import HodgeProofHP.Stage5ThetaJensenCellsBatch079

/-! Trust audits of all 1600 kernel certificates, in batches of twenty. -/

#print axioms HodgeProofHP.hpThetaJensenCellsBatch000_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch001_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch002_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch003_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch004_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch005_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch006_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch007_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch008_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch009_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch010_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch011_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch012_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch013_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch014_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch015_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch016_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch017_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch018_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch019_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch020_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch021_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch022_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch023_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch024_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch025_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch026_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch027_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch028_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch029_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch030_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch031_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch032_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch033_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch034_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch035_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch036_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch037_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch038_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch039_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch040_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch041_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch042_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch043_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch044_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch045_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch046_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch047_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch048_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch049_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch050_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch051_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch052_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch053_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch054_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch055_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch056_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch057_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch058_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch059_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch060_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch061_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch062_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch063_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch064_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch065_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch066_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch067_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch068_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch069_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch070_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch071_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch072_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch073_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch074_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch075_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch076_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch077_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch078_bounds
#print axioms HodgeProofHP.hpThetaJensenCellsBatch079_bounds
