import HodgeProofHP.Stage4ThetaFirstTraceXiRatio

/-!
Audit the exact theta definitions and available bounds before
proving numerical moment and energy estimates.
-/

open MeasureTheory

namespace HodgeProofHP

#print hpRiemannThetaKernel
#print hpRiemannThetaLogProfile
#print hpRiemannThetaDifferentialKernel

#print hpThetaPhiMomentZero
#print hpThetaPhiMomentTwo
#print hpThetaFirstTraceEnergy
#print hpThetaXiMomentRatio

#check hpRiemannThetaDifferentialKernel_continuous
#check hpRiemannThetaDifferentialKernel_exp_weighted_tendsto_zero
#check hpThetaPhi_integrableOn
#check hpThetaPhi_secondMoment_integrableOn
#check hpRiemannThetaDifferentialKernel_hankel_weight_integrableOn

#check hpThetaFirstTraceEnergy_ne_ratio_of_bounds
#check hpThetaFirstTraceEnergy_ne_xi_secondDeriv_ratio_of_bounds

end HodgeProofHP
