import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch00
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch01
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch02
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch03
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch04
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch05
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch06
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch07
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch08
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch09
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch10
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch11
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch12
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch13
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch14
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch15
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch16
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch17
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch18
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch19
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch20
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch21
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch22
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch23
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch24
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch25
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch26
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch27
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch28
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch29
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch30
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch31
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch32
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch33
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch34
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch35
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch36
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch37
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch38
import HodgeProofHP.Stage4ThetaEnergyUpperCertificateBatch39

/-! All eight hundred interval upper certificates. -/

#print axioms HodgeProofHP.hpThetaEnergyUpper_interval_0
#print axioms HodgeProofHP.hpThetaEnergyUpper_interval_799
