import HodgeProofHP.Stage4ThetaNormalizedXiFourthDerivative
import HodgeProofHP.Stage4ThetaPhiMomentIntegrability

/-!
Audit the existing theta moment integrability results before extending
the cosine integral derivative calculation to fourth order.
-/

namespace HodgeProofHP

#check hpThetaPhi_exp_weighted_integrableOn
#check hpThetaPhi_integrableOn
#check hpThetaPhi_secondMoment_integrableOn
#check hpRiemannThetaDifferentialKernel_continuous
#check hpRiemannXiCritical_eq_differentialKernel_cosine_integral
#check hpThetaNormalizedXiFourthTraceCoefficient_eq_xi_ratio

#print axioms hpThetaPhi_exp_weighted_integrableOn
#print axioms hpThetaPhi_secondMoment_integrableOn
#print axioms hpThetaNormalizedXiFourthTraceCoefficient_eq_xi_ratio

end HodgeProofHP
